#!/usr/bin/env bash
set -euo pipefail


# =========================
# Config
# =========================
PROGRAMS_DIR="programs"

create_dirs() {
  # create_dirs <macro_dir> <exercise_name>
  # Creates: programs/<macro>/<exercise>/{data,plot,script}
  local macro_dir="$1"          # e.g. programs/error_analysis
  local exercise_name="$2"      # e.g. Ex1_1
  local exercise_dir="${macro_dir%/}/${exercise_name}"

  mkdir -p "${exercise_dir}/data" "${exercise_dir}/plot" "${exercise_dir}/script"
  echo "$exercise_dir"
}

update_dirs() {
  # update_dirs <exercise_dir>
  local exercise_dir="$1"
  mkdir -p "${exercise_dir%/}/data" "${exercise_dir%/}/plot" "${exercise_dir%/}/script"
}

create_cmake() {
  # create_cmake <exercise_dir>
  # Overwrites exercise CMakeLists.txt for the new structure.
  local exercise_dir="${1%/}"                           # programs/<macro>/<exercise>
  local rel="${exercise_dir#${PROGRAMS_DIR}/}"          # <macro>/<exercise>

  # Option 1 (recommended): call centralized add_exercise() helper (naming updates in one place)
  cat > "${exercise_dir}/CMakeLists.txt" <<EOF
# AUTOGENERATED (overwrite ok)
add_exercise(${rel})
EOF
}

create_subdirectories() {
  # create_subdirectories <macro_dir>
  # Two jobs:
  #  2) For each exercise folder, ensure main.c exists + write its CMakeLists + aux dirs
  local macro_dir="${1%/}"                  # programs/<macro>
  local macro_name="${macro_dir##*/}"       # <macro>

  # Walk exercises under this macro
  for exercise_dir in "${macro_dir}"/*/; do
    [[ -d "$exercise_dir" ]] || continue

    # Ensure aux dirs exist
    update_dirs "$exercise_dir"

    # Standardize source location: main.c in the exercise dir
    if [[ ! -f "${exercise_dir}/main.c" ]]; then
      # If there's exactly one .c file, rename it to main.c
      shopt -s nullglob
      c_files=("${exercise_dir}"/*.c)
      shopt -u nullglob

      if [[ ${#c_files[@]} -eq 1 ]]; then
        mv "${c_files[0]}" "${exercise_dir}/main.c"
      fi
    fi

    # Write exercise CMakeLists if main.c exists
    if [[ -f "${exercise_dir}/main.c" ]]; then
      create_cmake "$exercise_dir"
    fi
  done
}


# =========================
# Main
# =========================
main() {
  if [[ ! -d "$PROGRAMS_DIR" ]]; then
    echo "Error: '${PROGRAMS_DIR}/' not found (run from repo root)."
    exit 1
  fi

  # For each macro folder under programs/, generate macro + exercise cmake files
  for macro_dir in "${PROGRAMS_DIR}"/*/; do
    [[ -d "$macro_dir" ]] || continue
    create_subdirectories "$macro_dir"
  done

  echo "Done."
}

main "$@"


